#!/usr/bin/env bash
# SSH client configuration
# configured to use the private key ~/.ssh/school
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
