#!/usr/bin/env bash
# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Ensure that nginx is listening on port 80
sudo sed -i 's/\blisten 80\b/listen 80 default_server/g' /etc/nginx/sites-available/default

# Reload nginx to apply the changes
sudo /etc/init.d/nginx reload

# Create an HTML file with the required content
echo "Holberton School" | sudo tee /var/www/html/index.html

# Check if Nginx is serving the page correctly using curl
response=$(curl -s http://127.0.0.1)

# Check if the response contains "Holberton School"
if [[ $response == *"Holberton School"* ]]; then
    echo "Nginx configured successfully. Test passed!"
else
    echo "Something went wrong. Check Nginx logs for more information."
fi
