#!/usr/bin/env bash

# Install Nginx using Homebrew
brew install nginx

# Create necessary directories
sudo mkdir -p /usr/local/var/www/html

# Create the HTML file
echo "Holberton School for the win!" | sudo tee /usr/local/var/www/html/index.html > /dev/null

# Start Nginx service
brew services start nginx

# Confirm Nginx is listening on port 80
lsof -i :80
